# Generated by Django 4.2.4 on 2023-09-04 09:06

import uuid

from django.db import migrations, models

import points.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.PositiveSmallIntegerField(verbose_name="Value")),
                ("active_from", models.DateTimeField(verbose_name="Active from")),
                ("active_before", models.DateTimeField(verbose_name="Active before")),
                (
                    "is_multiple",
                    models.BooleanField(default=False, verbose_name="Multiple"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "code",
                    models.CharField(
                        default=points.models.generate_code,
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
