# Generated by Django 4.2.4 on 2023-09-04 09:35

import uuid

from django.db import migrations, models

import points.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Coupon name", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        help_text="Coupon value", verbose_name="Value"
                    ),
                ),
                (
                    "active_from",
                    models.DateTimeField(
                        help_text="2023-01-01 00:00:00", verbose_name="Active from"
                    ),
                ),
                (
                    "active_before",
                    models.DateTimeField(
                        help_text="2023-12-31 23:59:59", verbose_name="Active before"
                    ),
                ),
                (
                    "is_multiple",
                    models.BooleanField(
                        default=False, help_text="Multiple use", verbose_name="Multiple"
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "code",
                    models.CharField(
                        default=points.models.generate_code,
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
